# Autoscaling settings
autoscaling_buffer_pools: "worker"
autoscaling_buffer_cpu_scale: "1"
autoscaling_buffer_memory_scale: "0.85"
autoscaling_buffer_cpu_reserved: "1"
autoscaling_buffer_memory_reserved: "1500Mi"
{{if eq .Environment "production"}}
autoscaling_buffer_pods: "3"
{{else}}
autoscaling_buffer_pods: "0"
{{end}}
